AutoTrader/AutoTrader/Models/Cars/CarDetailsModel.cs
using AutoTrader.Data;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AutoTrader.Models.Cars
{
    public class CarDetailsModel
    {
        public int Id { get; set; }

        public string Make { get; set; }
        
        public string Model { get; set; }
        
        public int Year { get; set; }

        public string Color { get; set; }

        public double Engine { get; set; }

        public EngineType EngineType { get; set; }

        public VehicleType VehicleType { get; set; }

        public int? Power { get; set; }

        public decimal Price { get; set; }
        
        public string ImageUrl { get; set; }

        public bool IsSold { get; set; }

        public int TotalRents { get; set; }

        public string ContactInformation { get; set; }
    }
}

AutoTrader/AutoTrader/Models/Cars/CarListingModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AutoTrader.Models.Cars
{
    public class CarListingModel
    {
        public int Id { get; set; }

        public string Make { get; set; }

        public string Model { get; set; }

        public int Year { get; set; }

        public decimal Price { get; set; }

        public string ImageUrl { get; set; }

        public bool IsSold { get; set; }    
    }
}

AutoTrader/AutoTrader/Models/Cars/CreateCarModel.cs
using AutoTrader.Data;
using AutoTrader.Infrastructure;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AutoTrader.Models.Cars
{
    public class CreateCarModel
    {
        [Display(Name = "Vehicle type")]
        [ScaffoldColumn(false)]
        public VehicleType VehicleType { get; set; }

        [Required]
        [MaxLength(40)]
        public string Make { get; set; }

        [Required]
        public string Model { get; set; }

        [Range(1950, 2017)]
        public int Year { get; set; }

        public string Color { get; set; }

        public double Engine { get; set; }

        [Display(Name = "Engine type")]
        [ScaffoldColumn(false)]
        public EngineType EngineType { get; set; }

        public int? Power { get; set; }

        [Display(Name = "Price in BGN")]
        public decimal Price { get; set; }

        [Required]
        [Display(Name = "Image URL")]
        [Url]
        [ImageUrl]
        public string ImageUrl { get; set; }
    }
}

AutoTrader/AutoTrader/Controllers/CarsController.cs
using AutoTrader.Data;
using AutoTrader.Models.Cars;
using AutoTrader.Models.Leasing;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace AutoTrader.Controllers
{
    public class CarsController : Controller
    {
        public ActionResult All(
            int page = 1, 
            string user = null,
            string search = null)
        {
            var db = new CarsDbContext();

            var pageSize = 5;

            var carsQuery = db.Cars.AsQueryable();

            if (search != null)
            {
                carsQuery = carsQuery
                    .Where(c => c.Make.ToLower().Contains(search.ToLower()) ||
                    c.Model.ToLower().Contains(search.ToLower()));
            }

            if (user != null)
            {
                carsQuery = carsQuery
                    .Where(c => c.Owner.Email == user);
            }

            var cars = carsQuery
                .OrderByDescending(c => c.Id)
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .Select(c => new CarListingModel
                {
                    Id = c.Id,
                    ImageUrl = c.ImageUrl,
                    Make = c.Make,
                    Model = c.Model,
                    Year = c.Year,
                    Price = c.Price,
                    IsSold = c.IsSold
                })
                .ToList();

            ViewBag.CurrentPage = page;

            return View(cars);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(CreateCarModel CarModel)
        {
            if (CarModel != null && this.ModelState.IsValid)
            {
                var ownerId = this.User.Identity.GetUserId();

                var car = new Car
                {
                    VehicleType = CarModel.VehicleType,
                    Make = CarModel.Make,
                    Model = CarModel.Model,
                    Color = CarModel.Color,
                    Engine = CarModel.Engine,
                    EngineType = CarModel.EngineType,
                    ImageUrl = CarModel.ImageUrl,
                    Power = CarModel.Power,
                    Price = CarModel.Price,
                    Year = CarModel.Year,
                    OwnerId = ownerId
                };

                var db = new CarsDbContext();
                db.Cars.Add(car);
                db.SaveChanges();

                return RedirectToAction("Details", new { id = car.Id });
            }

            return View(CarModel);
        }

        public ActionResult Details(int id)
        {
            var db = new CarsDbContext();

            var car = db.Cars
                .Where(c => c.Id == id)
                .Select(c => new CarDetailsModel
                {
                    Id = c.Id,
                    Color = c.Color,
                    Engine = c.Engine,
                    EngineType = c.EngineType,
                    ImageUrl = c.ImageUrl,
                    Make = c.Make,
                    Model = c.Model,
                    Power = c.Power,
                    Price = c.Price,
                    Year = c.Year,
                    IsSold = c.IsSold,
                    TotalRents = c.Leasings.Count(),
                    ContactInformation = c.Owner.Email
                })
                .FirstOrDefault();

            if (car == null)
            {
                return HttpNotFound();
            }

            return View(car);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Sold(LeasingCarModel leasingCarModel)
        {
            if (leasingCarModel.Months < 1 || leasingCarModel.Months > 24)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var db = new CarsDbContext();

            var car = db.Cars
                .Where(c => c.Id == leasingCarModel.CarId)
                .Select(c => new
                {
                    c.IsSold,
                    c.Price,
                    c.ImageUrl,
                    FullName = c.Make + " " + c.Model + " (" + c.Year + ")"
                })
                .FirstOrDefault();

            if (car == null || car.IsSold)
            {
                return HttpNotFound();
            }

            leasingCarModel.CarName = car.FullName;
            leasingCarModel.CarImageUrl = car.ImageUrl;
            leasingCarModel.Price = car.Price;
            leasingCarModel.TotalPrice = car.Price / leasingCarModel.Months;

            return View(leasingCarModel);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Sold(int carId, int months)
        {
            var db = new CarsDbContext();

            var car = db.Cars
                .Where(c => c.Id == carId)
                .FirstOrDefault();

            var userId = this.User.Identity.GetUserId();

            if (car == null || car.IsSold || car.OwnerId == userId)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var leasing = new Leasing
            {
                CarId = carId,
                Months = months,
                SoldOn = DateTime.Now,
                UserId = userId,
                TotalPrice = car.Price
            };

            car.IsSold = true;

            db.Leasings.Add(leasing);
            db.SaveChanges();

            return RedirectToAction("Details", new { id = car.Id });
        }
    }
}

AutoTrader/AutoTrader/Controllers/LinksController.cs
using System.Web.Mvc;

namespace AutoTrader.Controllers
{
    public class LinksController : Controller
    {
        public ActionResult Bikes()
        {
            return View();
        }

        public ActionResult Caravans()
        {
            return View();
        }

        public ActionResult Cars()
        {
            return View();
        }

        public ActionResult Farm()
        {
            return View();
        }

        public ActionResult Motors()
        {
            return View();
        }
        
        public ActionResult TopMarques()
        {
            return View();
        }

        public ActionResult Trucks()
        {
            return View();
        }

        public ActionResult Vans()
        {
            return View();
        }
    }
}

AutoTrader/AutoTrader/Views/Links/Caravans.cshtml
<div>
    <p class="lead text-center"><img src="~/Image/MyCompanyLogo.jpg" width="400" height="200" class="img-thumbnail" /></p>
</div>
<div>
    <p class="text-center">
        <h1 class="text-center text-danger">How to choose the right caravan</h1>
    </p>
    <p>
    <p>
        So you’ve made the first decision – to buy a caravan – but where do you go from here? The choice is bewildering. Prices vary from £500 to £50,000 and you could base your decision on anything, from the colour of the furnishing to the country of manufacture. Where should you start? And will you get a better ’van if you pay more? 
    </p>
    <p>
        This Data Sheet offers a few pointers by helping you ask the right questions and consider your requirements before making an investment.
    </p>
    <p>
        <img class="col-md-4 img-responsive" src="~/Image/caravan2.jpg" />
        <img class="col-md-4 img-responsive" src="~/Image/caravan3.jpg" />
        <img class="col-md-4 img-responsive" src="~/Image/caravan1.jpg" />
    </p>
    <p>

         Take a look at these handy sections designed to guide you through the decision making process:
    </p>
    <ul>
        <li>
            Don't buy the first caravan you see
        </li>
        <li>
            Proper preparation prevents poor purchases
        </li>
        <li>
            Identify your ideal caravan layout
        </li>
        <li>
            Be wary of deals that are too good to be true
        </li>
        <li>
            Think before you buy a caravan on web auctions
        </li>
        <li>
            Pay close attention to the body
        </li>
        <li>
            Don't forget the dreaded damp test
        </li>
        <li>
            Don't be afraid of an old caravan
        </li>
        <li>
            Think about the aftersales service
        </li>
        <li>
            Check all the documents
        </li>
    </ul>

    <p>
        Is your car suitable to tow?
    </p>
    <p>
        The weight of your caravan should never exceed the weight of your car – your car manufacturer handbook should give you the maximum weight your car can tow. Basically, the heavier your car and the lighter your caravan the safer your outfit should be.       
    </p>
    <div>
        We recommend that the weight of your caravan with its contents should not exceed 85% of the car’s kerb, or unladen, weight. 
    </div>

</div>

<div class="btn btn-default">
    @Html.ActionLink("Back to top", "Caravans", "Links")
</div>

AutoTrader/AutoTrader/Views/Links/Cars.cshtml
<div>
    <p class="lead text-center"><img src="~/Image/MyCompanyLogo.jpg" width="400" height="200" class="img-thumbnail" /></p>
</div>
<div>
    <p class="text-center">
        <h1 class="text-center text-danger">How to choose the right car</h1>
    </p>
    <p>
    <p>
        As a car shopper, you have hundreds of choices when it comes to picking a new ride. While there’s something for every buyer, finding that perfect match isn’t always easy. Do you want a sports car but need an SUV? How critical are safety and fuel economy? Will that full-size truck fit in your garage? Do you need something that can drive off paved roads, or do your wheels never leave the pavement? How many people do you need to carry, and do you need to carry a lot of cargo?
    </p>
    <p>
        Finding the right ride involves finding the nexus of what you want and what you need. Fortunately, there are lots of tools available to help you narrow your search, including U.S. News & World Report’s new car rankings, used car rankings, and vehicle comparison tool.
    </p>
    <p>
        <img class="col-md-4 img-responsive" src="~/Image/car1.jpg" />
        <img class="col-md-4 img-responsive" src="~/Image/car3.jpg" />
        <img class="col-md-4 img-responsive" src="~/Image/car2.jpg" />
    </p>
    <p>
        Take a look at these handy sections designed to guide you through the decision making process:

    </p>
    
    <ul>
        <li>
            What Kind of Car Do You Want?
        </li>
        <li>
            What Kind of Car Do You Need?
        </li>
        <li>
            Who/What You Carry?
        </li>
        <li>
            Where You Live?
        </li>
        <li>
            What You Do?
        </li>
        <li>
            What You Can Afford?
        </li>
        <li>
            What You Can Compromise On?
        </li>
    </ul>

    <p>
        Additional information about Load type that may help you:
    </p>
    <div>
        First you need to decide on the ideal payload for your car.  To do this check the size, weight and volume of your typical load.  Here are some typical weights and sizes to help give you an idea:
    </div>
    <br />
    <div>
        <ul>
            <li>
                A bag of dry sand -1330kg per cubic metre
            </li>
            <li>
                A Euro pallet -1200mm x 800mm
            </li>
            <li>
                Baled hay - Up to 225kg per cubic metre
            </li>
            <li>
                A bag of cement - 25kg or 50kg
            </li>
            <li>
                A sheet of MDF - 2440mm x 1220mm x 15mm weighs 30-37kg
            </li>
            <li>
                A bag of potatoes - 50kg
            </li>
            <li>
                A tin of 5L paint - 7kg
            </li>
        </ul>
    </div>

</div>

<div class="btn btn-default">
    @Html.ActionLink("Back to top", "Cars", "Links")
</div>

AutoTrader/AutoTrader/Views/Links/Farm.cshtml
<div>
    <p class="lead text-center"><img src="~/Image/MyCompanyLogo.jpg" width="400" height="200" class="img-thumbnail" /></p>
</div>
<div>
    <p class="text-center">
        <h1 class="text-center text-danger">How to choose the right farm</h1>
    </p>
    
    <p>
        Determining which tractor is best for your needs requires much research and consideration. Let us help you narrow down the various configurations and features available.
    </p>
    <p>
        <img class="col-md-4 img-responsive" src="~/Image/farm1.jpg" />
        <img class="col-md-4 img-responsive" src="~/Image/farm2.jpg" />
        <img class="col-md-4 img-responsive" src="~/Image/farm3.jpg" />
    </p>
    <p>
        You need the right tractor for your job with the correct equipment which is right for now and the future.  So how do you make your mind up?
    </p>
    Take a look at these handy sections designed to guide you through the decision making process:
    <ul>
        <li>
            Tractor Options
        </li>
        <li>
            Consider your property
        </li>
        <li>
            Sizes and configurations
        </li>
        <li>
            Transmission options
        </li>
        <li>
            Horsepower types
        </li>
        <li>
            Hydraulics and three-point hitch
        </li>
        <li>
            Front-wheel assist
        </li>
        <li>
            Dealer service
        </li>
        <li>
            Operator's platform
        </li>
        <li>
            Rear componentry
            <li>
                Power take-off (PTO)
            </li>
            <li>
                Hydraulic coupler
            </li>
        <li>
            Hydraulic cylinder
        </li>
        <li>
            Draft link
        </li>
        <li>
            Lifting link
        </li>
        <li>
            Compression link
        </li>
    </ul>

    
</div>

<div class="btn btn-default">
    @Html.ActionLink("Back to top", "Farm", "Links")
</div>

AutoTrader/AutoTrader/Views/Links/Motors.cshtml
<div>
    <p class="lead text-center"><img src="~/Image/MyCompanyLogo.jpg" width="400" height="200" class="img-thumbnail" /></p>
</div>
<div>
    <p class="text-center">
        <h1 class="text-center text-danger">How to choose the right motorbike</h1>
    </p>
    <p>
    <p>
        So you've decided to buy a motorcycle and hit the open road. Before you do, you should consider the number of different bike options out there.
    </p>
    <p>
        Motorcycles come in all shapes and sizes, and offer different advantages or disadvantages based on things like how, when, and why you want to ride and your level of experience.
    </p>
    <p>
        <img class="col-md-4 img-responsive" src="~/Image/motor1.jpg" />
        <img class="col-md-4 img-responsive" src="~/Image/motor2.jpg" />
        <img class="col-md-4 img-responsive" src="~/Image/motor3.jpg" />
    </p>
    <p>
        Take a look at these handy sections designed to guide you through the decision making process:

    </p>
    <ul>
        <li>
            How will you be using your motorbike?
        </li>
        <li>
            How much would a motorbike cost to run?
        </li>
        <li>
            How to finance a motorbike?
        </li>
        <li>
            How do I know what type of motorbike to choose?
        </li>
        <li>
            How do I choose the components of a motorbike?
        </li>
        <li>
            How will you be using your motorbike?
        </li>
    </ul>

    
</div>

<div class="btn btn-default">
    @Html.ActionLink("Back to top", "Motors", "Links")
</div>

AutoTrader/AutoTrader/Views/Links/Plant.cshtml
<div>
    <p class="lead text-center"><img src="~/Image/MyCompanyLogo.jpg" width="400" height="200" class="img-thumbnail" /></p>
    <h2 class="text-center text-danger">Discover your perfect car, Here’s a quick and easy way to find a car that suits you.</h2>
</div>
<div>
    <p class="text-center">
        <a href="/Cars/Create" class="btn btn-primary btn-lg">Sell My Car</a>
        <a href="/Cars/All" class="btn btn-primary btn-lg">Buy New Or Used</a>
    </p>
</div>


<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AutoTrader/AutoTrader/Views/Links/TopMarques.cshtml
<div>
    <p class="lead text-center"><img src="~/Image/MyCompanyLogo.jpg" width="400" height="200" class="img-thumbnail" /></p>
</div>
<div>
    <p class="text-center">
        <h1 class="text-center text-danger">How to choose the right luxury car</h1>
    </p>
    <p>
        You may have just started a new business, perhaps your business is expanding so you need a luxury car or you just want to replace an old one.  Whatever your situation choosing the best vehicle is important.
    </p>
    <p>
        <img class="col-md-4 img-responsive" src="~/Image/luxury1.jpg" />
        <img class="col-md-4 img-responsive" src="~/Image/luxury2.png" />
        <img class="col-md-4 img-responsive" src="~/Image/luxury3.jpg" />
    </p>
    <p>
        You need the right luxury car for your job with the correct equipment which is right for now and the future.  So how do you make your mind up?
    </p>
    Take a look at these handy sections designed to guide you through the decision making process:
    <ul>
        <li>
            How will you be using your van?
        </li>
        <li>
            How much would a van cost to run?
        </li>
        <li>
            How to finance a van?
        </li>
        <li>
            How do I know what type of van to choose?
        </li>
        <li>
            How do I choose the components of a van?
        </li>
        <li>
            How will you be using your van?
        </li>
    </ul>

    <p>
        Additional information about Load type that may help you:
    </p>
    <div>
        First you need to decide on the ideal payload for your van.  To do this check the size, weight and volume of your typical load.  Here are some typical weights and sizes to help give you an idea:
    </div>
    <br />
    <div>
        <ul>
            <li>
                A bag of dry sand -1330kg per cubic metre
            </li>
            <li>
                A Euro pallet -1200mm x 800mm
            </li>
            <li>
                Baled hay - Up to 225kg per cubic metre
            </li>
            <li>
                A bag of cement - 25kg or 50kg
            </li>
            <li>
                A sheet of MDF - 2440mm x 1220mm x 15mm weighs 30-37kg
            </li>
            <li>
                A bag of potatoes - 50kg
            </li>
            <li>
                A tin of 5L paint - 7kg
            </li>
        </ul>
    </div>

</div>

<div class="btn btn-default">
    @Html.ActionLink("Back to top", "TopMarques", "Links")
</div>

AutoTrader/AutoTrader/Views/Links/Trucks.cshtml
<div>
    <p class="lead text-center"><img src="~/Image/MyCompanyLogo.jpg" width="400" height="200" class="img-thumbnail" /></p>
</div>
<div>
    <p class="text-center">
        <h1 class="text-center text-danger">How to choose the right truck</h1>
    </p>
    <p>
        We can help you to choose the right truck for your truck camper.  We know that it can be a complex process.  Not only are there six truck manufacturers and four truck levels to choose from, but each truck comes in a myriad of styles, bed lengths, engine types, and option packages.
    </p>
    <p>
        Of course the number one issue when buying a truck for a truck camper is payload capacity. That’s not to say that paint color and leather seats aren’t important, but payload is the one, two, three, four, or even five thousand pound gorilla in the bed.
    </p>
    <p>
        <img class="col-md-4 img-responsive" src="~/Image/truck1.jpg" />
        <img class="col-md-4 img-responsive" src="~/Image/truck3.jpg" />
        <img class="col-md-4 img-responsive" src="~/Image/truck2.jpg" />
    </p>
    <p>
        You need the right van for your job with the correct equipment which is right for now and the future.  So how do you make your mind up?
    </p>
    Take a look at these handy sections designed to guide you through the decision making process:
    <div>
        <ul>
            <li>
                How will you be using your truck?
            </li>
            <li>
                How much would a van cost to truck?
            </li>
            <li>
                How to finance a truck?
            </li>
            <li>
                How do I know what type of truck to choose?
            </li>
            <li>
                How do I choose the components of a truck?
            </li>
            <li>
                How will you be using your truck?
            </li>
        </ul>
    </div>
   
    <div class="text-left">
        Additional information about Load type that may help you. First you need to decide on the ideal payload for your truck.  To do this check the size, weight and volume of your typical load.  Here are some typical weights and sizes to help give you an idea:
    </div>
    <br />
    <div>
        <ul>
            <li>
                A bag of dry sand -1330kg per cubic metre
            </li>
            <li>
                A Euro pallet -1200mm x 800mm
            </li>
            <li>
                Baled hay - Up to 225kg per cubic metre
            </li>
            <li>
                A bag of cement - 25kg or 50kg
            </li>
            <li>
                A sheet of MDF - 2440mm x 1220mm x 15mm weighs 30-37kg
            </li>
            <li>
                A bag of potatoes - 50kg
            </li>
            <li>
                A tin of 5L paint - 7kg
            </li>
        </ul>
    </div>

</div>

<div class="btn btn-default">
    @Html.ActionLink("Back to top", "Trucks", "Links")
</div>

AutoTrader/AutoTrader/Views/Links/Vans.cshtml
<div>
    <p class="lead text-center"><img src="~/Image/MyCompanyLogo.jpg" width="400" height="200" class="img-thumbnail"/></p>
</div>
<div>
    <p class="text-center">
        <h1 class="text-center text-danger">How to choose the right van</h1>
    </p>
    <p>
        <p>
        You may have just started a new business, perhaps your business is expanding so you need a van or you just want to replace an old one.  Whatever your situation choosing the best vehicle is important.
        </p>
    <p>
        <img class="col-md-4 img-responsive" src="~/Image/van2.jpg" />
        <img class="col-md-4 img-responsive" src="~/Image/van3.jpg" />
        <img class="col-md-4 img-responsive" src="~/Image/van1.jpg" />
    </p>
    <div>

    <p class="text-left mt-60">
        <br />
        <br />
        <br/>
        You need the right van for your job with the correct equipment which is right for now and the future.  So how do you make your mind up?
    </p>
    </div>
        <p>
        
        
        <ul>
            <li>
                How will you be using your van?
            </li>
            <li>
                How much would a van cost to run?
            </li>
            <li>
                How to finance a van?
            </li>
            <li>
                How do I know what type of van to choose?
            </li>
            <li>
                How do I choose the components of a van?
            </li>
            <li>
                How will you be using your van?
            </li>
        </ul>
        
        <p>
        Additional information about Load type that may help you:
        </p>
    <div>
        First you need to decide on the ideal payload for your van.  To do this check the size, weight and volume of your typical load.  Here are some typical weights and sizes to help give you an idea:
    </div>
    <br/>
    <div>
        <ul>
            <li>
                A bag of dry sand -1330kg per cubic metre
            </li>
            <li>
                A Euro pallet -1200mm x 800mm
            </li>
            <li>
                Baled hay - Up to 225kg per cubic metre
            </li>
            <li>
                A bag of cement - 25kg or 50kg
            </li>
            <li>
                A sheet of MDF - 2440mm x 1220mm x 15mm weighs 30-37kg
            </li>
            <li>
                A bag of potatoes - 50kg
            </li>
            <li>
                A tin of 5L paint - 7kg
            </li>
        </ul>
    </div>  
    
</div>

<div class="btn btn-default">
    @Html.ActionLink("Back to top", "Vans", "Links")
</div>
        